# Generated by Django 5.2.4 on 2025-08-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_portion', '0003_rename_appoint_fee_doctormodel_consultantfee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctormodel',
            old_name='name_doctor',
            new_name='name',
        ),
    ]
