# Generated by Django 5.2.4 on 2025-08-23 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_portion', '0002_bookingmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctormodel',
            old_name='appoint_fee',
            new_name='consultantFee',
        ),
        migrations.RenameField(
            model_name='doctormodel',
            old_name='profile_doctor',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='doctormodel',
            old_name='core_education',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='doctormodel',
            old_name='topic_education',
            new_name='speciality',
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='doctormodel',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
